[versions]
android-sdk-compile = "36"
android-sdk-min = "31"
android-sdk-target = "36"
android-build-tools = "36.1.0"

android-gradle-plugin = "9.0.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.17.0" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version = "1.2.1" }
androidx-window = { module = "androidx.window:window", version = "1.5.1" }
google-material = { module = "com.google.android.material:material", version = "1.13.0" }
osmdroid = { module = "org.osmdroid:osmdroid-android", version = "6.1.20" }

# Testing dependencies
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
junit = { module = "junit:junit", version = "4.13.2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }